### ISSUE TITLE
Class 'DraperStudio\Picible\PicibleServiceProvider' not found

### ISSUE THREAD

**Issue by philippejadin** [DraperStudio/Laravel-Picible#2]
Sorry if it's a newbie question but on a fresh laravel install, I get 
`Class 'DraperStudio\Picible\PicibleServiceProvider' not found`

when doing  `php artisan vendor:publish`

**Comment by DraperStudio** [comment]
https://github.com/DraperStudio/Laravel-Picible/blob/master/src/ServiceProvider.php
